name: Push To GitHub Pages On Land to master
on: [push]
jobs:
  push-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy Files
        run: |
          mkdir public
          cp -vr -t public img/ css/ index.html
      - name: Upload to GitHub Pages
        if: success() && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public/
          jekyll: false
          verbose: true
          fqdn: m3rlin.net
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}